# Generated by Django 3.2.16 on 2023-04-28 11:26

from django.db import migrations, models
import forge.utils.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=forge.utils.base.random_string, max_length=128, primary_key=True, serialize=False)),
                ('screens', models.TextField(blank=True, default='', null=True)),
                ('screens_compiled', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
