package rules.principal;

import java.util.List;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;

import agents.Principal;


rule "Send email"
    when
        // passed time = 24h
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: Principal(
            lastEmailSentTime before[24h] ts
        )
    then
        // agent.sendEmail(List.of("ndmitrovic@mioc.hr"), "Novi odgovori učenika", "Bok, Moli je. Skupila sam odgovore učenika u proteklih 24h i šaljem ti ih u privitku. https://docs.google.com/spreadsheets/d/1fLIn_xpPIxCBteodfglxNe-hUoPVzJ7rzHabUDZGKpk/edit?usp=sharing");
        Log.warn("Not sending mail to principal because it is currently disabled!");
end
