# Generated by Django 3.2.16 on 2023-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('config_id', models.CharField(max_length=255, unique=True)),
                ('intro_text', models.TextField(default='Hej, ja sam Moli', help_text='Describe the persona talking to the user.', verbose_name='Persona')),
                ('qa_prompt', models.TextField(default='Answer the question based on the context above. \nOnly answer questions about following topics: MIOC. \nIf the question isn\'t about these topics or the answer cannot be found in the context, \nsay "I don\'t know". Give short and precise answers, summarizing the key points. \nYou are friendly, patient and compassionate. \nAnswer complex questions in simple terms, over several turns. \nKeep the client engaged and always ask if they understood you. \nEnd messages in punctuation marks.', help_text='Write instructions for how the assistant should answer the user questions.', verbose_name='Instructions')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_assistant', models.BooleanField(default=False)),
                ('knowledge_base', models.ManyToManyField(blank=True, help_text="Select files you want to add as assistant's knowledge.", limit_choices_to={'item_status': 'ADDED AS KNOWLEDGE'}, to='knowledge.File')),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'My assistants',
            },
        ),
    ]
