# Generated by Django 3.2.16 on 2023-06-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_auto_20230605_0748'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='assistant_configuration',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Unregistered Client']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistants.assistantconfiguration', verbose_name='Dedicated assistant'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='time_zone',
            field=models.CharField(default='America/New_York', max_length=255),
        ),
    ]
