package rules.boss;

import agents.Boss;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;


rule "Send email"
    when
        // passed time = 24h
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: Boss(
            lastEmailSentTime before[24h] ts
        )
    then
        agent.sendEmail(List.of('ndmitrovic@mioc.hr'), "Novi odgovori učenika", "Bok, Moli je. Skupila sam odgovore učenika u proteklih 24h i šaljem ti ih u privitku.") // spreadsheet link missing
