package rules.smith;

import agents.Smith;


import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;

import com.mindsmiths.gsheetsAdapter.GSheetsAdapterAPI
import com.mindsmiths.gsheetsAdapter.reply.Spreadsheet

// Connecting to google spreadsheet
rule "Get Google Sheets"
    when
        Heartbeat(now: timestamp) from entry-point "signals"
        agent: Smith(lastTableUpdate == null || lastTableUpdate before[30s] now)
    then
        modify(agent){
            setLastTableUpdate(now)
        };
        GSheetsAdapterAPI.getSpreadsheet();
end

// Rule for processing the sheet
rule "Process Sheet"
    when
        spreadsheet: Spreadsheet() from entry-point "signals"
        agent: Smith()
    then
        agent.processSheet(spreadsheet);
        //agent.getReview("karlo.visnjovski@gmail","6","oke je");
        agent.newAgent();
        delete(spreadsheet);
end
