package rules.smith;

import agents.Smith;
import signals.AddReview;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;

import com.mindsmiths.gsheetsAdapter.GSheetsAdapterAPI
import com.mindsmiths.gsheetsAdapter.reply.Spreadsheet

// Connecting to google spreadsheet
rule "Get Google Sheets"
    when
        Heartbeat(now: timestamp) from entry-point "signals"
        agent: Smith(lastTableUpdate == null || lastTableUpdate before[30s] now)
    then
        modify(agent){
            setLastTableUpdate(now)
        };
        GSheetsAdapterAPI.getSpreadsheet();
end

// Rule for processing the sheet
rule "Process Sheet"
    when
        spreadsheet: Spreadsheet() from entry-point "signals"
        agent: Smith()
    then
        agent.processSheet(spreadsheet);
        delete(spreadsheet);
end

rule "Add Review"
    when
        signal: AddReview() from entry-point "signals"
        agent: Smith()
    then
        agent.addReviewToSheet(signal.getEmail(), signal.getGender(), signal.getAge(), signal.getRating(), signal.getFeedback());
        delete(signal);
end