package rules.moliWapp;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.model.Initialize;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.infobipAdapter.models.InfobipReceivedMessage;
import agents.MoliWapp;

rule "Send initial message"
    when
        signal: Initialize() from entry-point "signals"
        agent: MoliWapp()
    then
        Log.info("MoliWapp has been initialized.");
end

rule "Handle message"
    when
        signal: InfobipReceivedMessage(message: message) from entry-point "signals"
    then
        // What are we expected to do here?
        
end