global:
  env:
    PULSAR_URL: {{ env.PULSAR_URL }}
    PULSAR_ENDPOINT_URL: {{ env.PULSAR_ENDPOINT_URL }}

    MONGO_CLIENT_HOST: {{ env.MONGO_CLIENT_HOST }}
    MONGO_CLIENT_USERNAME: {{ env.MONGO_CLIENT_USERNAME }}

    POSTGRES_CLIENT_HOST: {{ env.POSTGRES_CLIENT_HOST }}
    POSTGRES_CLIENT_PORT: {{ env.POSTGRES_CLIENT_PORT }}
    POSTGRES_CLIENT_USERNAME: {{ env.POSTGRES_CLIENT_USERNAME }}

    REDIS_CLIENT_HOST: {{ env.REDIS_CLIENT_HOST }}
    REDIS_CLIENT_PORT: {{ env.REDIS_CLIENT_PORT }}

    INTERNAL_CONTROL_PANEL_URL: '{{ env.CONTROL_PANEL_URL | default("http://localhost:8100", true) }}'

  secrets:
    MONGO_CLIENT_CONNECTION_STRING: {{ env.MONGO_CLIENT_CONNECTION_STRING }}
    MONGO_CLIENT_PASSWORD: {{ env.MONGO_CLIENT_PASSWORD }}

    POSTGRES_CLIENT_PASSWORD: {{ env.POSTGRES_CLIENT_PASSWORD }}
services:
  armory:
    command:
      build: "./build.sh"
      run: "armory runserver 8000"
    env:
      SITE_URL: '{{ env.ARMORY_SITE_URL | default("http://localhost:8000", true) }}'
    port: 8000
  control-panel:
    port: 8100
    env:
      SITE_URL: '{{ env.CONTROL_PANEL_URL | default("http://localhost:8100", true) }}'
  infobip-adapter:
    command:
      run: "uvicorn infobip_adapter.service:app --port=8002"
      cwd: "."
    port: 8002
  dashboard:
    env:
      SITE_URL: '{{ env.DASHBOARD_SITE_URL | default("http://localhost:8001", true) }}'
    port: 8001
  calendar-adapter:
    port: 8003
    command:
      run: "uvicorn calendar_adapter.service:app --port=8003"
    env:
      SERVICE_HOST: 'http://localhost:8003'
  mitems:
    env:
      SITE_URL: localhost:8004
    port: 8004