package rules.clientAgent;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.model.Initialize;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.sdk.utils.Utils;
import signals.AddReview;
import agents.ClientAgent;

/*
rule "Remind user to fill in the NPS survey"
    when
        signal: Heartbeat(ts: timestamp) from entry-point "signals"
        agent: ClientAgent(reminderSent == false,
                    age == null,
                    lastNpsSent before[72h] ts)
    then
        modify(agent) { setReminderSent(true) }
        agent.sendWhatsappTextMessage(agent.getReminderMessage());
        delete(signal);
end

rule "Send a new NPS message after 3 months"
    when
        signal: Heartbeat(ts: timestamp) from entry-point "signals"
        agent: ClientAgent(lastNpsSent before[90d] ts)
    then
        agent.sendNpsMessage();
        modify(agent) {
            setLastNpsSent(Utils.now()),
            setReminderSent(false),
            setFeedback(""),
            setRating(-1)
        }
end
*/