com.mindsmiths.armory.event.Submit:
  - !GetAgentByConnection
    connectionName: armory
    connectionField: connectionId
com.mindsmiths.armory.event.UserDisconnected:
  - !GetAgentByConnection
    connectionName: armory
    connectionField: connectionId
com.mindsmiths.infobipAdapter.models.InfobipReceivedMessage:
  - !GetAgentByConnection
    connectionName: phone
    connectionField: from
com.mindsmiths.infobipAdapter.models.InfobipSentMessage:
  - !GetAgentByConnection
    connectionName: phone
    connectionField: to
com.mindsmiths.discordAdapter.message.DiscordReceivedMessage:
  - !AlwaysSendTo
    agentId: "HITL"
com.mindsmiths.discordAdapter.message.DiscordSentMessage:
  - !AlwaysSendTo
    agentId: "HITL"
