package rules.boss;

import agents.Boss;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;


rule "Send email"
    when
        // passed time = 24h
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: Boss(
            memory.isEmpty() == false, //je li ova linija bitna?
            lastEmailSentTime before[24h] ts
        )
    then
        agent.sendEmail(List.of('ndmitrovic@mioc.hr'), "Novi review", "Tekst maila + link spreadsheeta") //reba osmisliti tekst
