package rules.ravnatelj;

import agents.Ravnatelj;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;

// rule za slanje maila svaki dan

rule "Send email"
    when
        // proslo vrijeme = 24h
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: Ravnatelj(
            memory.isEmpty() == false, //je li ova linija bitna?
            lastEmailSentTime before[24h] ts
        )
    then
        agent.sendEmail(List.of('ndmitrovic@mioc.hr'), "Novi review", "Tekst maila + link spreadsheeta") //reba osmisliti tekst
